backend/models/Pay.php
<?php

namespace backend\models;

use Yii;
use frontend\models\rebate\UserPay;

/**
 * This is the model class for table "pay".
 *
 * @property integer $id
 * @property string $name
 * @property string $tip
 * @property integer $status
 * @property string $code
 *
 * @property UserPay[] $userPays
 */
class Pay extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pay';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['status'], 'integer'],
            [['name', 'tip', 'code'], 'string', 'max' => 250],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Платежная система',
            'tip' => 'Пример',
            'code' => 'Код',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserPays()
    {
        return $this->hasMany(UserPay::className(), ['pay_id' => 'id']);
    }
}

frontend/controllers/PayController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use backend\models\Pay;
use frontend\models\rebate\PaymentChangeForm;
use frontend\models\rebate\OutputForm;
use common\models\rebate\Output;
use yii\web\NotFoundHttpException;
use common\models\User;
use frontend\models\rebate\UserPay;

/**
 * Site controller
 */
class PayController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],

                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }


    public function init()
    {
        parent::init();
        $this->layout = 'vpluse';
    }

    /**
     * Lists all User Payments.
     * @return mixed
     */
    public function actionPaymentDetails()
    {
        $payments = Pay::find()->where('status=1')->joinWith([
            'userPays' => function ($query) {
                $query->onCondition(['user_pay.user_id' => Yii::$app->user->id]);
            },
        ])->all();

        $payments_details = [];
        foreach ($payments as $key => $payment) {
            $payments_details[$key]['id'] = $payment->id;
            $payments_details[$key]['name'] = $payment->name;
            $payments_details[$key]['value'] = $payment->userPays ? $payment->userPays[0]->value : '-';
        }

        return $this->render('payment_details', [
            'payments_details' => $payments_details,
        ]);
    }

    /**
     * Change User Payments.
     * @param integer $pay_id
     * @return mixed
     */
    //change-payment-detail
    public function actionChangePaymentDetail($pay_id)
    {
        $user = $this->findModel(Yii::$app->user->id);
        $pay = Pay::find()->where('pay.id='. $pay_id)->joinWith([
            'userPays' => function ($query) {
                $query->onCondition(['user_pay.user_id' => Yii::$app->user->id]);
            },
        ])->one();

        $model = new PaymentChangeForm($user, $pay);

        if ($model->load(Yii::$app->request->post()) && $model->changePayment()) {
            Yii::$app->session->setFlash('success', 'Реквизиты успешно сохранены.');

            return $this->redirect(['payment-details']);
        } else {
            return $this->render('payment_change', [
                'model' => $model,
            ]);
        }

    }

    /**
     * Output money
     * @return mixed
     */
    public function actionOutput()
    {
        $service = isset($_SESSION['service']) ? $_SESSION['service'] : null;
        switch ($service) {
            case 'rebate' :
                echo $service_id = 1;
                break;
            case 'vps' :
                echo $service_id = 2;
                break;
            case 'bot' :
                echo $service_id = 3;
                break;
            default : $service_id = 0;
        }

        $model = new OutputForm();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $output_model = new Output();
            $output_model->id_user = Yii::$app->user->id;
            $output_model->amount = $model->credit;
            $payData = $model->paymentData();
            $output_model->payment_detail = $payData['payment_detail'];
            $output_model->payment = $payData['payment'];
            $output_model->service_id = $service_id;

            if ($output_model->save()) {
                $params =[
                    'id' => $output_model->id,
                    'amount' => $output_model->amount,
                    'payment_detail' => $output_model->payment_detail,
                ];
                //Уведомление для админа
                User::sendMailToAdmin(10, $params);
                //Уведомление для пользователя idUser
                $output_model->idUser->sendMail(11, $params);
                Yii::$app->session->setFlash('success', 'Заявка на вывод средств успешно отправлена');
            } else {
                Yii::$app->session->setFlash('error', 'Не удалось создать заявку');
            }
        }

        return $this->render('output', [
            'model' => $model,
        ]);

    }

    /**
     * Check user payment detail
     */
    public function actionGetPayment()
    {
        if(!Yii::$app->request->isAjax) {
            exit('go home!');
        }
        $user_payment_detail = '';
        if($post = Yii::$app->request->post()) {
            if(isset($post['pay_id'])) {
                $user_payment_detail = UserPay::find()
                    ->where(['user_id'=> Yii::$app->user->id, 'pay_id' => $post['pay_id']])
                    ->one();
            }
            if($user_payment_detail) {
                exit($user_payment_detail->value);
            }
        }
        exit($user_payment_detail);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/views/pay/output.php
<?php
use frontend\assets\OutputAsset;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use frontend\widgets\StaticBlockWidget;

/* @var $this yii\web\View */
/* @var $model frontend\models\rebate\OutputForm */

$this->title = 'Вывести средства';
OutputAsset::register($this);

?>
<div class="content__section">
    <div class="info">
        <span class="title-block"><?= Html::encode($this->title) ?></span>
        <div class="info__block half_left">

            <div class="form">

                <?php $form = ActiveForm::begin(); ?>

                <?= $form->field($model, 'pay_system')->dropDownList($model->paySystems, ['id'=>'pay_system']) ?>
                <div id="not_have_payment_detail" class="alert alert-danger">
                    Прежде чем выводить средства на эту платежную систему, вам нужно указать ваш кошелек.
                    Сделать это можно в разделе
                    <a href="<?= Url::to(['/pay/payment-details']) ?>">«Платежные реквизиты»</a>
                </div>

                <?= $form->field($model, 'payment_detail')->textInput(['id'=>'payment_detail','readonly' => true]) ?>

                <?= $form->field($model, 'credit')->textInput() ?>


                <div class="form-group">
                    <?= Html::submitButton('Снять средства', ['class' => 'btn btn-primary']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
        <div class="info__block half_right">
            <?= StaticBlockWidget::widget(['id' => 3]) ?>
        </div>
    </div>
</div>

frontend/views/pay/payment_change.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\rebate\PaymentChangeForm */

$this->title = $model->payment_detail ? 'Изменение' : 'Добавление';
$this->title .= ' реквизитов для ' . $model->paymentName;
?>
<div class="content__section">
    <div class="info">
        <span class="title-block"><?= Html::encode($this->title) ?></span>
        <div class="info__block">

            <div class="form">

                <?php $form = ActiveForm::begin(); ?>

                <?= $form->field($model, 'payment_detail')->textInput(['maxlength' => true, 'placeholder' => $model->paymentTip]) ?>

                <div class="info__title">Внимание!</div>
                <p class="info__text">
                    Нужно ввести пароль от личного кабинета Вплюсе, а не от платежной системы!
                </p>
                <?= $form->field($model, 'currentPassword')->passwordInput(['maxlength' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
                </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</div>

frontend/views/pay/payment_details.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $payments_details array */

$this->title = 'Платежные реквизиты';
?>

<div class="content__section">
    <div class="info">
        <span class="title-block"><?= Html::encode($this->title) ?></span>
        <div class="info__block">
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>Платежная система</th>
                    <th>Реквизиты</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($payments_details as $payment) {
                ?>
                    <tr>
                        <td><?= $payment['name'] ?></td>
                        <td><?= $payment['value'] ?></td>
                        <td><?= Html::a('Добавить/Изменить', [Url::to(['/pay/change-payment-detail']), 'pay_id' => $payment['id']], ['class' => 'btn btn-primary']) ?></td>
                    </tr>
                <?php
                }
                ?>
                </tbody>
            </table>
        </div>
    </div>
</div>